import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Providers from "./Providers";
import { ClerkProvider } from "@clerk/nextjs";
 

const kanit = Kanit({
  weight: '200',
  subsets: ["latin","thai"],
});

 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${kanit.className} antialiased`}
        >
          <Providers>
            <Navbar />
            <main className="container  ">{children}</main>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
